leftnav:
- identifier: b35783dd-50ad-8272-683b-fc5f49f6a845
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: d0de6121-14b3-13d6-1594-c39c3ee7ff5c
  name: Readings
  url: /pages/readings/
  weight: 20
- identifier: 4dcffd6b-d753-b3c9-9f75-de06871b3ca7
  name: Some Reading Strategies for History Courses
  parent: d0de6121-14b3-13d6-1594-c39c3ee7ff5c
  url: /pages/readings/some-reading-strategies-for-history-courses
  weight: 30
- identifier: 2af84446-3d51-5113-f350-4f97b02e2f10
  name: Assignments
  url: /pages/assignments/
  weight: 40
- identifier: 10c9c5d0-49be-8eaf-3ab2-f3568ed3d861
  name: Paper 1
  parent: 2af84446-3d51-5113-f350-4f97b02e2f10
  url: /pages/assignments/paper-1
  weight: 50
- identifier: e4d4d220-2710-1d53-b465-8c76f37491ea
  name: Paper 2
  parent: 2af84446-3d51-5113-f350-4f97b02e2f10
  url: /pages/assignments/paper-2
  weight: 60
- identifier: 45d2f37b-7403-cac7-8862-aa15b908ada8
  name: Paper 2 Revision
  parent: 2af84446-3d51-5113-f350-4f97b02e2f10
  url: /pages/assignments/paper-2-revision
  weight: 70
- identifier: 2d216fef-2dd6-a75c-2019-dcab4d6ff4c1
  name: Paper 3
  parent: 2af84446-3d51-5113-f350-4f97b02e2f10
  url: /pages/assignments/paper-3
  weight: 80
